version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "6500:5432"
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - app_network

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./.env
    ports:
      - "5050:80"
    networks:
      - app_network

  api:
    build: .
    container_name: rust_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      # Use the service name 'postgres' instead of localhost
      DATABASE_URL: postgresql://admin:saisab@postgres:5432/rust_sqlx?schema=public
    volumes:
      - ./src:/app/src:ro
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  progresDB:
