name: Docker Image CI for GHCR

on:
  workflow_run:
    workflows: ["Run Tests"] # This ensures this workflow runs after the test workflow
    types:
      - completed

jobs:
  Build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username saisab29 --password ${{secrets.GH_PAT}} ghcr.io
          docker build . --tag ghcr.io/cardanoapi/cardanoapi.io-ghcr:latest
          docker push ghcr.io/cardanoapi/cardanoapi.io-ghcr:latest
